version: '3'
services:
  app:
    build: .
    restart: always
    ports: 
      - "8000"
    links: 
      - mongo
      - redis
    volumes: 
      - .:/usr/src/app
    environment: 
      NODE_ENV: development
    depends_on: 
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports: 
      - "27017"
  redis:
    image: redis
    restart: always
    ports: 
      - "6379"
 

  
