version: '3'
services:
  app:
    image: tantalum/nodetomic-api-swagger 
    restart: always
    ports: 
      - "8000"
    links: 
      - mongo
      - redis
    volumes: 
      - .:/usr/src/app
    depends_on: 
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports: 
      - "27017"
  redis:
    image: redis
    restart: always
    ports: 
      - "6379"
 

  
